% script_demo_predictiveSafetySpeedPlanning
%
% Demonstrates the complete predictive safety speed-planning framework on
% the mapped Penn State Test Track.
%
% The script:
%
% - Loads the mapped inner and outer track boundaries.
% - Generates an approximate center path.
% - Places a fixed physical obstacle at the validated Test 11 location.
% - Evaluates the same obstacle in counter-clockwise and clockwise travel.
% - Compares stopping distance, path curvature, and friction allocation.
%
% The comparison speed is selected slightly below the minimum physical
% cornering-speed limit in the analyzed region. This isolates the effect of
% simultaneous lateral and longitudinal friction use without introducing a
% prior curve-speed reduction.
%
% Run script_demo_2026VDLibrary before this script to initialize the
% Vehicle Dynamics library and its dependencies.
%
% DEPENDENCIES:
%
% fcn_VD_computePredictiveSafetySpeedProfile
% fcn_Path_findIntersectionsBetweenPaths
% fcn_VD_buildSampleRoad
% fcn_VD_computeSpeedProfile
%
% REVISION HISTORY:
%
% 2026_07_18 by Jaime Rodriguez
% - Replaced the original synthetic demonstration with the validated
%   mapped-track CW versus CCW comparison.
% - Added curvature and friction-allocation figures.
% - Fixed the physical obstacle at the location validated in Test 11.
%
% TO-DO:
%

% Prep the workspace

close all;
clear;
clc;


% Load the mapped Test Track boundaries

currentFilePath = which( ...
    'script_demo_predictiveSafetySpeedPlanning.m');

assert(~isempty(currentFilePath), ...
    'The demonstration script could not locate itself on the MATLAB path.');

[currentFolder, ~, ~] = ...
    fileparts(currentFilePath);

repoRoot = fullfile( ...
    currentFolder, ...
    '..', ...
    '..');

dataFile = fullfile( ...
    repoRoot, ...
    'Data', ...
    'testTrackBoundariesXY.mat');

assert(isfile(dataFile), ...
    'The Test Track boundary data file could not be found.');

loadedData = load(dataFile);

assert(isfield(loadedData, 'outerBoundaryXY'), ...
    'The data file must contain outerBoundaryXY.');

assert(isfield(loadedData, 'innerBoundaryXY'), ...
    'The data file must contain innerBoundaryXY.');

outerBoundaryXY = ...
    loadedData.outerBoundaryXY;

innerBoundaryXY = ...
    loadedData.innerBoundaryXY;

% Remove invalid rows

outerBoundaryXY = outerBoundaryXY( ...
    ~any(isnan(outerBoundaryXY),2), :);

innerBoundaryXY = innerBoundaryXY( ...
    ~any(isnan(innerBoundaryXY),2), :);

assert(size(outerBoundaryXY,1) >= 3, ...
    'The outer boundary must contain at least three valid points.');

assert(size(innerBoundaryXY,1) >= 3, ...
    'The inner boundary must contain at least three valid points.');

% Remove repeated closing points temporarily

closureTolerance = 1e-6;

if norm( ...
        outerBoundaryXY(end,:) - ...
        outerBoundaryXY(1,:)) < closureTolerance

    outerBoundaryXY = ...
        outerBoundaryXY(1:end-1,:);

end

if norm( ...
        innerBoundaryXY(end,:) - ...
        innerBoundaryXY(1,:)) < closureTolerance

    innerBoundaryXY = ...
        innerBoundaryXY(1:end-1,:);

end

% Ensure that both boundaries follow the same direction

outerBoundaryAreaPath = [
    outerBoundaryXY
    outerBoundaryXY(1,:)
];

innerBoundaryAreaPath = [
    innerBoundaryXY
    innerBoundaryXY(1,:)
];

outerSignedArea = 0.5 * sum( ...
    outerBoundaryAreaPath(1:end-1,1) .* ...
    outerBoundaryAreaPath(2:end,2) - ...
    outerBoundaryAreaPath(2:end,1) .* ...
    outerBoundaryAreaPath(1:end-1,2));

innerSignedArea = 0.5 * sum( ...
    innerBoundaryAreaPath(1:end-1,1) .* ...
    innerBoundaryAreaPath(2:end,2) - ...
    innerBoundaryAreaPath(2:end,1) .* ...
    innerBoundaryAreaPath(1:end-1,2));

if sign(outerSignedArea) ~= sign(innerSignedArea)

    innerBoundaryXY = ...
        flipud(innerBoundaryXY);

end

% Align the initial points of the two boundaries

distanceToOuterStart = sqrt(sum( ...
    (innerBoundaryXY - outerBoundaryXY(1,:)).^2, ...
    2));

[~, closestInnerStartIndex] = ...
    min(distanceToOuterStart);

innerBoundaryXY = [
    innerBoundaryXY(closestInnerStartIndex:end,:)
    innerBoundaryXY(1:closestInnerStartIndex-1,:)
];

% Close the boundaries

outerBoundaryClosed = [
    outerBoundaryXY
    outerBoundaryXY(1,:)
];

innerBoundaryClosed = [
    innerBoundaryXY
    innerBoundaryXY(1,:)
];

% Calculate normalized station along both boundaries

outerSegmentVectors = diff( ...
    outerBoundaryClosed, ...
    1, ...
    1);

outerSegmentLengths = sqrt(sum( ...
    outerSegmentVectors.^2, ...
    2));

outerStation = [
    0
    cumsum(outerSegmentLengths)
];

innerSegmentVectors = diff( ...
    innerBoundaryClosed, ...
    1, ...
    1);

innerSegmentLengths = sqrt(sum( ...
    innerSegmentVectors.^2, ...
    2));

innerStation = [
    0
    cumsum(innerSegmentLengths)
];

assert(outerStation(end) > 0, ...
    'The outer boundary must have positive length.');

assert(innerStation(end) > 0, ...
    'The inner boundary must have positive length.');

outerNormalizedStation = ...
    outerStation ./ outerStation(end);

innerNormalizedStation = ...
    innerStation ./ innerStation(end);

% Resample the two boundaries on a common normalized grid

numberOfCenterPathPoints = 1200;

commonNormalizedStation = linspace( ...
    0, ...
    1, ...
    numberOfCenterPathPoints + 1)';

outerBoundaryResampledClosed = [
    interp1( ...
        outerNormalizedStation, ...
        outerBoundaryClosed(:,1), ...
        commonNormalizedStation, ...
        'linear'), ...
    interp1( ...
        outerNormalizedStation, ...
        outerBoundaryClosed(:,2), ...
        commonNormalizedStation, ...
        'linear')
];

innerBoundaryResampledClosed = [
    interp1( ...
        innerNormalizedStation, ...
        innerBoundaryClosed(:,1), ...
        commonNormalizedStation, ...
        'linear'), ...
    interp1( ...
        innerNormalizedStation, ...
        innerBoundaryClosed(:,2), ...
        commonNormalizedStation, ...
        'linear')
];

% Generate the center path

centerPathCandidate = 0.5 .* ( ...
    outerBoundaryResampledClosed(1:end-1,:) + ...
    innerBoundaryResampledClosed(1:end-1,:));

outerBoundaryResampled = ...
    outerBoundaryResampledClosed(1:end-1,:);

innerBoundaryResampled = ...
    innerBoundaryResampledClosed(1:end-1,:);

% Normalize the point ordering so predictedPathCCW is counter-clockwise

centerPathAreaPath = [
    centerPathCandidate
    centerPathCandidate(1,:)
];

centerPathSignedArea = 0.5 * sum( ...
    centerPathAreaPath(1:end-1,1) .* ...
    centerPathAreaPath(2:end,2) - ...
    centerPathAreaPath(2:end,1) .* ...
    centerPathAreaPath(1:end-1,2));

if centerPathSignedArea < 0

    centerPathCandidate = ...
        flipud(centerPathCandidate);

    outerBoundaryResampled = ...
        flipud(outerBoundaryResampled);

    innerBoundaryResampled = ...
        flipud(innerBoundaryResampled);

end

predictedPathCCW = ...
    centerPathCandidate;

predictedPathCW = ...
    flipud(predictedPathCCW);

centerPathClosed = [
    predictedPathCCW
    predictedPathCCW(1,:)
];

% Place the fixed physical obstacle
%
% This location was selected and validated in Test 11. Using a fixed
% physical coordinate keeps the demonstration reproducible and separates
% scenario presentation from the obstacle-selection analysis performed in
% the test script.

validatedObstacleCenter = [
    441.120, ...
     97.029
];

distanceToValidatedObstacle = sqrt(sum( ...
    (predictedPathCCW - validatedObstacleCenter).^2, ...
    2));

[~, obstaclePathIndex] = ...
    min(distanceToValidatedObstacle);

obstacleCenter = ...
    predictedPathCCW(obstaclePathIndex,:);

numberOfPathPoints = ...
    size(predictedPathCCW,1);

previousObstacleIndex = mod( ...
    obstaclePathIndex - 2, ...
    numberOfPathPoints) + 1;

nextObstacleIndex = mod( ...
    obstaclePathIndex, ...
    numberOfPathPoints) + 1;

localTangent = ...
    predictedPathCCW(nextObstacleIndex,:) - ...
    predictedPathCCW(previousObstacleIndex,:);

localTangent = ...
    localTangent ./ norm(localTangent);

localNormal = [
    -localTangent(2), ...
     localTangent(1)
];

localTrackWidth = norm( ...
    outerBoundaryResampled(obstaclePathIndex,:) - ...
    innerBoundaryResampled(obstaclePathIndex,:));

obstacleLength = ...
    0.60 * localTrackWidth;

obstaclePath = [
    obstacleCenter - ...
    0.5 * obstacleLength * localNormal

    obstacleCenter + ...
    0.5 * obstacleLength * localNormal
];

% Define the planner settings

comparisonSpeed = 20.0;
muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = comparisonSpeed;
plannerSettings.U_initial  = comparisonSpeed;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

availableFrictionAcceleration = ...
    plannerSettings.lambda * ...
    muValue * ...
    plannerSettings.g;

% Compute the CCW profile

[UxDesiredCCW, roadCCW, intersectionPointsCCW, ...
 sCollisionCCW, ~, ~, speedProfileDataCCW] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPathCCW, ...
        obstaclePath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        []);

% Compute the CW profile

[UxDesiredCW, roadCW, intersectionPointsCW, ...
 sCollisionCW, ~, ~, speedProfileDataCW] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPathCW, ...
        obstaclePath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        []);

assert(size(intersectionPointsCCW,1) == 1, ...
    'The CCW path must have exactly one obstacle intersection.');

assert(size(intersectionPointsCW,1) == 1, ...
    'The CW path must have exactly one obstacle intersection.');

% Identify the final obstacle-related braking region
%
% The last continuous backward-binding interval connected to the obstacle
% is used. Earlier speed reductions may be associated with path curvature
% rather than the terminal obstacle constraint.

brakingDetectionTolerance = 1e-2;

nonObstacleSpeedLimitCCW = min( ...
    speedProfileDataCCW.U_forward, ...
    speedProfileDataCCW.U_corner);

brakingBindingMarginCCW = ...
    nonObstacleSpeedLimitCCW - ...
    speedProfileDataCCW.U_backward;

obstacleBrakingMaskCCW = ...
    brakingBindingMarginCCW > ...
    brakingDetectionTolerance;

lastNonBrakingIndexCCW = find( ...
    ~obstacleBrakingMaskCCW(1:end-1), ...
    1, ...
    'last');

if isempty(lastNonBrakingIndexCCW)

    obstacleBrakingIndexCCW = 1;

else

    obstacleBrakingIndexCCW = ...
        lastNonBrakingIndexCCW + 1;

end

sBrakingStartCCW = ...
    roadCCW.s(obstacleBrakingIndexCCW);

brakingDistanceCCW = ...
    sCollisionCCW - sBrakingStartCCW;

nonObstacleSpeedLimitCW = min( ...
    speedProfileDataCW.U_forward, ...
    speedProfileDataCW.U_corner);

brakingBindingMarginCW = ...
    nonObstacleSpeedLimitCW - ...
    speedProfileDataCW.U_backward;

obstacleBrakingMaskCW = ...
    brakingBindingMarginCW > ...
    brakingDetectionTolerance;

lastNonBrakingIndexCW = find( ...
    ~obstacleBrakingMaskCW(1:end-1), ...
    1, ...
    'last');

if isempty(lastNonBrakingIndexCW)

    obstacleBrakingIndexCW = 1;

else

    obstacleBrakingIndexCW = ...
        lastNonBrakingIndexCW + 1;

end

sBrakingStartCW = ...
    roadCW.s(obstacleBrakingIndexCW);

brakingDistanceCW = ...
    sCollisionCW - sBrakingStartCW;

% Shift station so the obstacle is at zero

relativeStationCCW = ...
    roadCCW.s - sCollisionCCW;

relativeStationCW = ...
    roadCW.s - sCollisionCW;

relativeBrakingStartCCW = ...
    sBrakingStartCCW - sCollisionCCW;

relativeBrakingStartCW = ...
    sBrakingStartCW - sCollisionCW;

% Calculate friction-allocation metrics

brakingRegionMaskCCW = ...
    roadCCW.s >= sBrakingStartCCW & ...
    roadCCW.s <= sCollisionCCW;

brakingRegionMaskCW = ...
    roadCW.s >= sBrakingStartCW & ...
    roadCW.s <= sCollisionCW;

combinedAccelerationCCW = sqrt( ...
    speedProfileDataCCW.a_x.^2 + ...
    speedProfileDataCCW.a_y.^2);

combinedAccelerationCW = sqrt( ...
    speedProfileDataCW.a_x.^2 + ...
    speedProfileDataCW.a_y.^2);

maximumLateralAccelerationCCW = max( ...
    abs(speedProfileDataCCW.a_y(brakingRegionMaskCCW)), ...
    [], ...
    'omitnan');

maximumLateralAccelerationCW = max( ...
    abs(speedProfileDataCW.a_y(brakingRegionMaskCW)), ...
    [], ...
    'omitnan');

maximumLateralFrictionUseCCW = ...
    maximumLateralAccelerationCCW / ...
    availableFrictionAcceleration;

maximumLateralFrictionUseCW = ...
    maximumLateralAccelerationCW / ...
    availableFrictionAcceleration;

brakingDistanceDifference = ...
    brakingDistanceCW - brakingDistanceCCW;

brakingDistancePercentageDifference = ...
    100 * brakingDistanceDifference / ...
    brakingDistanceCCW;

% Verify the physical cornering-speed margin in the plotted approach region

comparisonPlotDistance = max([ ...
    brakingDistanceCCW
    brakingDistanceCW
]);

cornerCheckDistance = ...
    comparisonPlotDistance + 5;

cornerCheckMaskCCW = ...
    relativeStationCCW >= -cornerCheckDistance & ...
    relativeStationCCW <= 0;

cornerCheckMaskCW = ...
    relativeStationCW >= -cornerCheckDistance & ...
    relativeStationCW <= 0;

kappaFloor = 1e-12;

uncappedCornerSpeedCCW = ...
    inf(size(roadCCW.kappa));

uncappedCornerSpeedCW = ...
    inf(size(roadCW.kappa));

curvedRoadMaskCCW = ...
    abs(roadCCW.kappa) > kappaFloor;

curvedRoadMaskCW = ...
    abs(roadCW.kappa) > kappaFloor;

uncappedCornerSpeedCCW(curvedRoadMaskCCW) = sqrt( ...
    availableFrictionAcceleration ./ ...
    abs(roadCCW.kappa(curvedRoadMaskCCW)));

uncappedCornerSpeedCW(curvedRoadMaskCW) = sqrt( ...
    availableFrictionAcceleration ./ ...
    abs(roadCW.kappa(curvedRoadMaskCW)));

minimumCornerSpeedCCW = min( ...
    uncappedCornerSpeedCCW(cornerCheckMaskCCW), ...
    [], ...
    'omitnan');

minimumCornerSpeedCW = min( ...
    uncappedCornerSpeedCW(cornerCheckMaskCW), ...
    [], ...
    'omitnan');

minimumPhysicalCornerSpeed = min( ...
    minimumCornerSpeedCCW, ...
    minimumCornerSpeedCW);

cornerSpeedMargin = ...
    minimumPhysicalCornerSpeed - comparisonSpeed;

% Perform concise integrity checks

frictionVerificationTolerance = ...
    1e-6 * max( ...
        1, ...
        availableFrictionAcceleration);

assert(abs(UxDesiredCCW(end)) < 1e-6, ...
    'The CCW profile must reach zero speed at the obstacle.');

assert(abs(UxDesiredCW(end)) < 1e-6, ...
    'The CW profile must reach zero speed at the obstacle.');

assert(all( ...
    combinedAccelerationCCW <= ...
    availableFrictionAcceleration + ...
    frictionVerificationTolerance), ...
    'The CCW profile violates the available friction limit.');

assert(all( ...
    combinedAccelerationCW <= ...
    availableFrictionAcceleration + ...
    frictionVerificationTolerance), ...
    'The CW profile violates the available friction limit.');

assert(cornerSpeedMargin > 0, ...
    ['The comparison speed must remain below the physical ', ...
     'cornering-speed limit in the analyzed region.']);

% Define consistent colors

ccwColor = [0 0.4470 0.7410];
cwColor  = [0.8500 0.3250 0.0980];

outerBoundaryColor = [0 0.4470 0.7410];
innerBoundaryColor = [0.8500 0.3250 0.0980];
centerPathColor = [0.9290 0.6940 0.1250];
obstacleColor = [0.4940 0.1840 0.5560];
intersectionColor = [0.4660 0.6740 0.1880];
referenceColor = [0.35 0.35 0.35];

% Plot the mapped track and fixed obstacle

geometryFigNum = 30012;

figure(geometryFigNum);
clf;
hold on;
grid on;
box on;
axis equal;

plot( ...
    outerBoundaryClosed(:,1), ...
    outerBoundaryClosed(:,2), ...
    '-', ...
    'Color', outerBoundaryColor, ...
    'LineWidth', 0.8, ...
    'DisplayName', 'Outer boundary');

plot( ...
    innerBoundaryClosed(:,1), ...
    innerBoundaryClosed(:,2), ...
    '-', ...
    'Color', innerBoundaryColor, ...
    'LineWidth', 0.8, ...
    'DisplayName', 'Inner boundary');

plot( ...
    centerPathClosed(:,1), ...
    centerPathClosed(:,2), ...
    '--', ...
    'Color', centerPathColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'Generated center path');

plot( ...
    obstaclePath(:,1), ...
    obstaclePath(:,2), ...
    '-', ...
    'Color', obstacleColor, ...
    'LineWidth', 4, ...
    'DisplayName', 'Fixed physical obstacle');

plot( ...
    intersectionPointsCCW(:,1), ...
    intersectionPointsCCW(:,2), ...
    'x', ...
    'Color', intersectionColor, ...
    'MarkerSize', 13, ...
    'LineWidth', 3, ...
    'DisplayName', 'Detected intersection');

xlabel('East [m]');
ylabel('North [m]');

title( ...
    'Mapped Test Track with fixed physical obstacle');

legend( ...
    'Location', ...
    'best');

% Plot the CW and CCW stopping profiles

speedComparisonFigNum = 30016;

figure(speedComparisonFigNum);
clf;
hold on;
grid on;
box on;

hSpeedCCW = plot( ...
    relativeStationCCW, ...
    UxDesiredCCW, ...
    '-', ...
    'Color', ccwColor, ...
    'LineWidth', 2.5, ...
    'DisplayName', sprintf( ...
        'CCW: braking distance %.2f m', ...
        brakingDistanceCCW));

hSpeedCW = plot( ...
    relativeStationCW, ...
    UxDesiredCW, ...
    '-', ...
    'Color', cwColor, ...
    'LineWidth', 2.5, ...
    'DisplayName', sprintf( ...
        'CW: braking distance %.2f m', ...
        brakingDistanceCW));

hBrakingCCW = xline( ...
    relativeBrakingStartCCW, ...
    ':', ...
    'Color', ccwColor, ...
    'LineWidth', 1.8, ...
    'DisplayName', 'CCW braking start');

hBrakingCW = xline( ...
    relativeBrakingStartCW, ...
    '--', ...
    'Color', cwColor, ...
    'LineWidth', 1.8, ...
    'DisplayName', 'CW braking start');

hObstacle = xline( ...
    0, ...
    '-', ...
    'Color', referenceColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

hPostedSpeed = yline( ...
    comparisonSpeed, ...
    ':', ...
    'Color', referenceColor, ...
    'LineWidth', 1.4, ...
    'DisplayName', 'Posted speed');

hBrakingCCW.Label = '';
hBrakingCW.Label = '';
hObstacle.Label = '';
hPostedSpeed.Label = '';

xlim([ ...
    -comparisonPlotDistance - 10, ...
    3]);

ylim([ ...
    0, ...
    1.08 * comparisonSpeed]);

xlabel('Station relative to obstacle [m]');
ylabel('Safe speed [m/s]');

title( ...
    'CW and CCW stopping profiles at the same physical obstacle');

legend( ...
    [ ...
    hSpeedCCW
    hSpeedCW
    hBrakingCCW
    hBrakingCW
    hObstacle
    hPostedSpeed
    ], ...
    'Location', ...
    'best');

% Plot path curvature during both approaches

curvatureComparisonFigNum = 30015;

figure(curvatureComparisonFigNum);
clf;
hold on;
grid on;
box on;

plot( ...
    relativeStationCCW, ...
    abs(roadCCW.kappa), ...
    '-', ...
    'Color', ccwColor, ...
    'LineWidth', 2.2, ...
    'DisplayName', 'CCW absolute curvature');

plot( ...
    relativeStationCW, ...
    abs(roadCW.kappa), ...
    '-', ...
    'Color', cwColor, ...
    'LineWidth', 2.2, ...
    'DisplayName', 'CW absolute curvature');

xline( ...
    relativeBrakingStartCCW, ...
    ':', ...
    'Color', ccwColor, ...
    'LineWidth', 1.5, ...
    'DisplayName', 'CCW braking start');

xline( ...
    relativeBrakingStartCW, ...
    ':', ...
    'Color', cwColor, ...
    'LineWidth', 1.5, ...
    'DisplayName', 'CW braking start');

xline( ...
    0, ...
    '-', ...
    'Color', referenceColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

xlim([ ...
    -comparisonPlotDistance - 10, ...
    3]);

xlabel('Station relative to obstacle [m]');
ylabel('Absolute curvature [1/m]');

title( ...
    'Path curvature during the CW and CCW approaches');

legend( ...
    'Location', ...
    'best');

% Plot longitudinal and lateral friction use

frictionComparisonFigNum = 30017;

figure(frictionComparisonFigNum);
clf;
hold on;
grid on;
box on;

plot( ...
    relativeStationCCW, ...
    abs(speedProfileDataCCW.a_x), ...
    '-', ...
    'Color', ccwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CCW longitudinal acceleration');

plot( ...
    relativeStationCW, ...
    abs(speedProfileDataCW.a_x), ...
    '-', ...
    'Color', cwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CW longitudinal acceleration');

plot( ...
    relativeStationCCW, ...
    abs(speedProfileDataCCW.a_y), ...
    '--', ...
    'Color', ccwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CCW lateral acceleration');

plot( ...
    relativeStationCW, ...
    abs(speedProfileDataCW.a_y), ...
    '--', ...
    'Color', cwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CW lateral acceleration');

yline( ...
    availableFrictionAcceleration, ...
    ':', ...
    'Color', referenceColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'Available friction acceleration');

xline( ...
    0, ...
    '-', ...
    'Color', referenceColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

xlim([ ...
    -comparisonPlotDistance - 10, ...
    3]);

ylim([ ...
    0, ...
    1.10 * availableFrictionAcceleration]);

xlabel('Station relative to obstacle [m]');
ylabel('Acceleration magnitude [m/s^2]');

title( ...
    'Longitudinal and lateral friction use before the obstacle');

legend( ...
    'Location', ...
    'best');

% Display the main results

fprintf('\nPredictive safety speed-planning demo\n');

fprintf('Comparison speed: %.3f m/s\n', ...
    comparisonSpeed);

fprintf('Minimum physical cornering-speed limit: %.3f m/s\n', ...
    minimumPhysicalCornerSpeed);

fprintf('Cornering-speed margin: %.3f m/s\n', ...
    cornerSpeedMargin);

fprintf('CCW braking distance: %.3f m\n', ...
    brakingDistanceCCW);

fprintf('CW braking distance: %.3f m\n', ...
    brakingDistanceCW);

fprintf('CW braking-distance increase: %.3f m\n', ...
    brakingDistanceDifference);

fprintf('Relative braking-distance increase: %.2f %%\n', ...
    brakingDistancePercentageDifference);

fprintf('Maximum CCW lateral friction use: %.2f %%\n', ...
    100 * maximumLateralFrictionUseCCW);

fprintf('Maximum CW lateral friction use: %.2f %%\n', ...
    100 * maximumLateralFrictionUseCW);
