%% script_test_fcn_VD_computePredictiveSafetySpeedProfile
%
% This script tests the function
%
%       fcn_VD_computePredictiveSafetySpeedProfile
%
% The function evaluates a predicted vehicle path against one or multiple
% path boundaries. If the predicted path intersects a boundary, the first
% intersection along the path is interpreted as a future safety violation.
%
% The existing speed planner is then used to calculate the maximum safe
% longitudinal-speed profile that satisfies the available-friction
% constraint and reaches zero speed at the collision station.
%
% When the requested initial speed is too high for the available stopping
% distance, the function also predicts the actual emergency-braking speed
% profile and the residual speed at the collision station.
%
% The following cases are evaluated:
%
% 1. A predicted path with one boundary intersection.
%
% 2. A predicted path with no boundary intersections.
%
% 3. A predicted path with two boundary intersections.
%
% 4. A curved predicted path, showing that the collision station is based
%    on accumulated distance along the path rather than global
%    x-coordinate.
%
% 5. A sample path generated using the Path Class Library.
%
% 6. A friction-coefficient sweep, showing the effect of available friction
%    on braking distance.
%
% 7. Several independent obstacles represented as multiple boundary paths.
%
% 8. A mapped pavement-boundary dataset used as a preliminary boundary
%    evaluation.
%
% 9. An infeasible stopping case in which the obstacle is too close for the
%    vehicle to stop from the requested initial speed. The test compares
%    the safe-speed limit with the predicted actual emergency-braking
%    profile and verifies the residual impact speed against an analytical
%    reference.
%
% 10. A Gao-based oval trajectory used as an additional non-trivial
%     predicted-path test case.
%
% 11. A mapped Test Track scenario comparing clockwise and
%     counter-clockwise approaches to the same physical obstacle. The test
%     evaluates the effect of path curvature on braking distance and on
%     longitudinal and lateral use of the available friction capacity.
%
% The tests verify:
%
% - Detected intersection points and first collision station.
% - Terminal-speed constraints.
% - Collision-related braking-start station and braking distance.
% - Normal operation when no collision is present.
% - Operation with multiple independent boundaries.
% - Sensitivity of braking distance to friction coefficient.
% - Prediction of residual impact speed when stopping is infeasible.
% - Compliance with the combined-friction constraint.
% - Direction-dependent braking behavior on the mapped Test Track.
%
% REVISION HISTORY:
%
% 2026_07_09 by Jaime Rodriguez
% - Created test script.
% - Added one-intersection test.
% - Added no-intersection test.
% - Added two-intersection test.
% - Added geometric visualization of the predicted path and boundary.
%
% 2026_07_10 by Jaime Rodriguez
% - Added tests for curved predicted paths.
% - Added tests for different friction coefficients.
% - Added tests for several independent obstacles.
% - Added tests using mapped Test Track boundaries.
% - Added test for infeasible stopping distance.
% - Added test using a Gao-based oval predicted path.
%
% 2026_07_18 by Jaime Rodriguez
% - Added prediction of the actual emergency-braking speed profile.
% - Added analytical verification of residual impact speed in Test 9.
% - Updated road geometry to use predicted-path curvature.
% - Added clockwise and counter-clockwise comparison at the same physical
%   obstacle in Test 11.
% - Added longitudinal and lateral friction-use analysis.
% - Added combined-friction and physical cornering-speed checks.
%
% TO-DO:
%
%% Prep the workspace
close all;
clear;
clc;


%% BASIC test 1 - One intersection
% Shared test settings

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.6;
plannerSettings.g          = 9.81;

% Inputs

predictedPath = [
     0  0
     5  0
    10  0
    15  0
];

boundaryPath = [
    8 -3
    8  3
];

figNum = 20001;

% Call function

[UxDesired, road, ~, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

% Print results

fprintf('Collision station: %.3f m\n', sCollision);
fprintf('Braking start: %.3f m\n', sBrakingStart);
fprintf('Braking distance: %.3f m\n', brakingDistance);
fprintf('Terminal speed: %.3f m/s\n', UxDesired(end));

% Mark braking start and collision station

figure(figNum);
hold on;

if ~isnan(sBrakingStart)

    xline( ...
        sBrakingStart, ...
        '--', ...
        sprintf( ...
            'Braking start: %.2f m', ...
            sBrakingStart));

end

xline( ...
    sCollision, ...
    ':', ...
    sprintf( ...
        'Collision: %.2f m', ...
        sCollision), ...
    'LineWidth', ...
    2);

% Standardize horizontal axis

xlim([ ...
    0, ...
    road.s(end)]);

xlabel('Station along predicted path [m]');

%% BASIC test 2 - No intersection
% Shared test settings

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.6;
plannerSettings.g          = 9.81;

% Inputs

predictedPath = [
     0  0
     5  0
    10  0
    15  0
];

boundaryPath = [
    8  1
    8  5
];

figNum = 20002;

% Call function

[UxDesired, road, intersectionPoints, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

% Print results

assert(isempty(intersectionPoints), ...
    'No intersections should be detected.');

assert(isnan(sCollision), ...
    'Collision station should be NaN.');

assert(isnan(sBrakingStart), ...
    'Braking start should be NaN.');

assert(isnan(brakingDistance), ...
    'Braking distance should be NaN.');

assert(~isempty(UxDesired), ...
    'A normal speed profile should still be calculated.');

assert(abs(UxDesired(end) - plannerSettings.U_posted) < 1e-6, ...
    'The vehicle should continue at the posted speed.');

% Mark braking start and collision station

figure(figNum);
hold on;


% Standardize plot axes

figure(figNum);
hold on;

xlim([ ...
    0, ...
    road.s(end)]);

ylim([ ...
    0, ...
    1.10 * max(UxDesired)]);

xlabel('Station along predicted path [m]');
ylabel('Speed [m/s]');

fprintf('\nNo-intersection test:\n');
fprintf('No collision detected.\n');
fprintf('The vehicle continues along the full predicted path.\n');
fprintf('Terminal speed: %.3f m/s\n', UxDesired(end));

%% BASIC test 3 - Two intersections
% Shared test settings

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.6;
plannerSettings.g          = 9.81;

% Inputs

predictedPath = [
     0  0
     5  0
    10  0
    15  0
];

boundaryPath = [
     4 -3
     4  3
    11  3
    11 -3
];

figNum = 20003;

% Call function

[UxDesired, ~, intersectionPoints, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

% Define common horizontal-axis limits for both figures

commonXLimits = [
    min(predictedPath(:,1)), ...
    max(predictedPath(:,1))
];

commonXTicks = ...
    commonXLimits(1):5:commonXLimits(2);

% Find which detected intersection is the first collision
[~, firstCollisionIndex] = ...
    min(abs(intersectionPoints(:,1) - sCollision));

% Plot braking profile result

figure(figNum);
hold on;

if ~isnan(sBrakingStart)

    xline(sBrakingStart, '--', ...
        sprintf('Braking start: %.2f m', sBrakingStart));

end

xline(sCollision, ':', ...
    sprintf('Collision: %.2f m', sCollision), ...
    'LineWidth', 2);

xlim([0 max(predictedPath(:,1))]);
ylim([0 1.10 * max(UxDesired)]);

xlabel('Station along predicted path [m]');
ylabel('Speed [m/s]');

% BASIC test 3.1 - Plot path and both intersections

geometryFigNum = 30003;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

plot(predictedPath(:,1), predictedPath(:,2), ...
    '-o', ...
    'DisplayName', 'Predicted path');

plot(boundaryPath(:,1), boundaryPath(:,2), ...
    '-s', ...
    'DisplayName', 'Boundary');

plot(intersectionPoints(:,1), intersectionPoints(:,2), ...
    'x', ...
    'MarkerSize', 12, ...
    'LineWidth', 2, ...
    'DisplayName', 'Intersections');

plot( ...
    intersectionPoints(firstCollisionIndex,1), ...
    intersectionPoints(firstCollisionIndex,2), ...
    'o', ...
    'MarkerSize', 10, ...
    'LineWidth', 2, ...
    'DisplayName', 'First collision');

xlabel('X [m]');
ylabel('Y [m]');
title('Predicted path and detected intersections');
legend('Location','best');

% Checks

assert(size(intersectionPoints,1) == 2, ...
    'Two intersections should be detected.');

assert(abs(sCollision - 4) < 1e-6, ...
    'The first collision should occur at s = 4 m.');

assert(abs(UxDesired(end)) < 1e-6, ...
    'Terminal speed should be zero.');

fprintf('\nTwo-intersection test:\n');
fprintf('Number of intersections: %d\n', ...
    size(intersectionPoints,1));
fprintf('First collision station: %.3f m\n', ...
    sCollision);
fprintf('Braking start: %.3f m\n', ...
    sBrakingStart);
fprintf('Braking distance: %.3f m\n', ...
    brakingDistance);

%% BASIC test 4 - Curved path with one intersection
% Shared test settings

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.6;
plannerSettings.g          = 9.81;

theta = linspace(0, pi/2, 50)';

radius = 10;

predictedPath = [
    radius*sin(theta), ...
    radius*(1-cos(theta))
];

boundaryPath = [
    7 -2
    7 12
];

figNum = 20004;

[~, ~, intersectionPoints, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

geometryFigNum = 30004;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

plot(predictedPath(:,1), predictedPath(:,2), ...
    '-o', ...
    'DisplayName', 'Curved predicted path');

plot(boundaryPath(:,1), boundaryPath(:,2), ...
    '-s', ...
    'DisplayName', 'Boundary');

plot(intersectionPoints(:,1), intersectionPoints(:,2), ...
    'x', ...
    'MarkerSize', 12, ...
    'LineWidth', 2, ...
    'DisplayName', 'Intersection');

xlabel('X [m]');
ylabel('Y [m]');
title('Curved path with one intersection');
legend('Location','best');

xlim([0 15]);

figure(figNum);
hold on;

if ~isnan(sBrakingStart)
    xline( ...
        sBrakingStart, ...
        '--', ...
        sprintf('Braking start: %.2f m', sBrakingStart));
end

xline( ...
    sCollision, ...
    ':', ...
    sprintf('Collision: %.2f m', sCollision), ...
    'LineWidth', 2);

xlim([0 15]);
ylim([0 1.10 * max(UxDesired)]);

fprintf('\nCurved-path test:\n');
fprintf('Collision station: %.3f m\n', sCollision);
fprintf('Collision X-coordinate: %.3f m\n', intersectionPoints(1,1));
fprintf('Braking start: %.3f m\n', sBrakingStart);
fprintf('Braking distance: %.3f m\n', brakingDistance);

%% BASIC test 5 - Sample trajectory from Laps Library

% Shared test settings

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.6;
plannerSettings.g          = 9.81;

% Input

pathsArray = fcn_Path_fillSamplePaths;
predictedPath = pathsArray{1};

boundaryPath = [
    50 10
    50 100
];

figNum = 20005;

[~, ~, intersectionPoints, ...
 sCollision, sBrakingStart, ~, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

% Adjust speed-profile axes

predictedPathStation = [ ...
    0; ...
    cumsum(vecnorm(diff(predictedPath), 2, 2)) ...
];

xlim([ ...
    0, ...
    predictedPathStation(end)]);

ylim([ ...
    0, ...
    ceil(1.10 * plannerSettings.U_posted)]);

xlabel('Station along predicted path [m]');
ylabel('Speed [m/s]');

% Display event information in a separate text box

eventInformation = sprintf( ...
    ['Braking start: %.2f m\n' ...
     'First collision: %.2f m\n' ...
     'Braking distance: %.2f m'], ...
    sBrakingStart, ...
    sCollision, ...
    brakingDistance);

annotation( ...
    'textbox', ...
    [0.65 0.18 0.22 0.14], ...
    'String', ...
    eventInformation, ...
    'FitBoxToText', ...
    'on', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.3 0.3 0.3], ...
    'FontSize', ...
    10);

geometryFigNum = 30005;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

xlim([ ...
    0, ...
    max(predictedPath(:,1)) + 5]);

ylim([ ...
    0, ...
    max(predictedPath(:,2)) + 5]);

plot(predictedPath(:,1), predictedPath(:,2), ...
    '.-', ...
    'LineWidth', 2, ...
    'DisplayName', 'Sample predicted path');

plot(boundaryPath(:,1), boundaryPath(:,2), ...
    '-', ...
    'LineWidth', 2, ...
    'DisplayName', 'Boundary');

plot(intersectionPoints(:,1), intersectionPoints(:,2), ...
    'x', ...
    'MarkerSize', 12, ...
    'LineWidth', 2, ...
    'DisplayName', 'Intersections');

xlabel('X [m]');
ylabel('Y [m]');

title('Sample path from Path Class Library');
legend('Location','best');


figure(figNum);
hold on;

% Braking-start line

if ~isnan(sBrakingStart)

    xline(sBrakingStart, ...
        '--', ...
        'LineWidth', ...
        1.2, ...
        'HandleVisibility', ...
        'off');

end

% First-collision line

if ~isnan(sCollision)

    xline( ...
        sCollision, ...
        ':', ...
        'LineWidth', ...
        2, ...
        'HandleVisibility', ...
        'off');

end

%% PARAMETRIC test 6 - Different friction coefficients

predictedPath = [
     0  0
     5  0
    10  0
    15  0
];

boundaryPath = [
    8 -3
    8  3
];

muValues = [0.2 0.4 0.6 0.8 1.0];

ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

comparisonFigNum = 20006;

figure(comparisonFigNum);
clf;
hold on;
grid on;

brakingStarts = NaN(length(muValues),1);
brakingDistances = NaN(length(muValues),1);

for iMu = 1:length(muValues)

    muValue = muValues(iMu);

    [UxDesired, road, ~, ...
     ~, sBrakingStart, brakingDistance, ...
     ~] = ...
        fcn_VD_computePredictiveSafetySpeedProfile( ...
            predictedPath, ...
            boundaryPath, ...
            muValue, ...
            plannerSettings, ...
            ds, ...
            []);

    brakingStarts(iMu) = sBrakingStart;
    brakingDistances(iMu) = brakingDistance;

    plot( ...
        road.s, ...
        UxDesired, ...
        'LineWidth', 2, ...
        'DisplayName', sprintf('\\mu = %.1f', muValue));

end

% Compute full predicted-path station

predictedPathStation = [0; ...
    cumsum(vecnorm(diff(predictedPath), 2, 2))];

xlabel('Station [m]');
ylabel('Speed [m/s]');
title('Effect of friction coefficient on braking profile');

xlim([0, ...
    predictedPathStation(end)]);

ylim([0, ...
    ceil(1.10 * plannerSettings.U_posted)]);

legend('Location','best');

fprintf('\nFriction comparison:\n');
fprintf('mu\tBraking start [m]\tBraking distance [m]\n');

for iMu = 1:length(muValues)

    fprintf( ...
        '%.1f\t%.3f\t\t\t%.3f\n', ...
        muValues(iMu), ...
        brakingStarts(iMu), ...
        brakingDistances(iMu));

end

assert(all(diff(brakingDistances) < 0), ...
    'Braking distance should decrease as friction increases.');

assert(all(diff(brakingStarts) > 0), ...
    'Braking should start later as friction increases.');

% Plot predicted path and boundary

geometryFigNum = 30006;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

plot( ...
    predictedPath(:,1), ...
    predictedPath(:,2), ...
    '-o', ...
    'LineWidth', ...
    1.5, ...
    'DisplayName', ...
    'Predicted path');

plot( ...
    boundaryPath(:,1), ...
    boundaryPath(:,2), ...
    '-', ...
    'LineWidth', ...
    1.5, ...
    'DisplayName', ...
    'Boundary');

xlabel('X [m]');
ylabel('Y [m]');
title('Trajectory used for friction-coefficient comparison');

xlim([0 15]);
ylim([-4 4]);

legend('Location','best');

%% BASIC test 7 - Several independent obstacles

predictedPath = [
     0  0
     5  0
    10  0
    15  0
];

boundaryPath = {
    [6 -2; 6 2]
    [10 -2; 10 2]
    [13 -2; 13 2]
};

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

figNum = 20007;

[UxDesired, ~, intersectionPoints, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

assert(size(intersectionPoints,1) == 3, ...
    'Three intersections should be detected.');

assert(abs(sCollision - 6) < 1e-6, ...
    'The first collision should occur at s = 6 m.');

assert(abs(UxDesired(end)) < 1e-6, ...
    'Terminal speed should be zero.');

figure(figNum);
hold on;

if ~isnan(sBrakingStart)
    xline( ...
        sBrakingStart, ...
        '--', ...
        sprintf('Braking start: %.2f m', sBrakingStart));
end

xline( ...
    sCollision, ...
    ':', ...
    sprintf('First collision: %.2f m', sCollision), ...
    'LineWidth', 2);

xlim([0 15]);
ylim([0, ...
    ceil(1.10 * plannerSettings.U_posted)]);

geometryFigNum = 30007;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

plot(predictedPath(:,1), predictedPath(:,2), ...
    '-o', ...
    'LineWidth', 2, ...
    'DisplayName', 'Predicted path');

for iBoundary = 1:length(boundaryPath)

    currentBoundaryPath = boundaryPath{iBoundary};

    plot( ...
        currentBoundaryPath(:,1), ...
        currentBoundaryPath(:,2), ...
        '-s', ...
        'LineWidth', 2, ...
        'DisplayName', sprintf('Obstacle %d', iBoundary));

end

plot(intersectionPoints(:,1), intersectionPoints(:,2), ...
    'x', ...
    'MarkerSize', 12, ...
    'LineWidth', 2, ...
    'DisplayName', 'Intersections');

xlabel('X [m]');
ylabel('Y [m]');
title('Several independent obstacles');
legend('Location','best');

xlim([0 15]);

fprintf('\nSeveral-obstacle test:\n');
fprintf('Number of intersections: %d\n', ...
    size(intersectionPoints,1));
fprintf('First collision station: %.3f m\n', ...
    sCollision);
fprintf('Braking start: %.3f m\n', ...
    sBrakingStart);
fprintf('Braking distance: %.3f m\n', ...
    brakingDistance);

%% BASIC test 8 - Mapped test-track boundaries
% 1. Load pavement boundaries
script_loadPavementBoundaries

% 2. Split at NaN rows
nanRows = any(isnan(pavementBoundaries), 2);

segmentStartIndices = find([true; nanRows(1:end-1)]);
segmentEndIndices = find([nanRows(2:end); true]);

boundaryPathsLatLon = cell(length(segmentStartIndices),1);

validBoundaryCount = 0;

for iSegment = 1:length(segmentStartIndices)

    currentSegment = pavementBoundaries( ...
        segmentStartIndices(iSegment):segmentEndIndices(iSegment), :);

    % Remove NaN rows
    currentSegment = currentSegment( ...
        ~any(isnan(currentSegment),2), :);

    % Keep only valid paths with at least two points
    if size(currentSegment,1) >= 2

        validBoundaryCount = validBoundaryCount + 1;

        boundaryPathsLatLon{validBoundaryCount,1} = ...
            currentSegment;

    end

end

% Remove unused empty cells
boundaryPathsLatLon = ...
    boundaryPathsLatLon(1:validBoundaryCount);

fprintf('\nMapped test-track boundaries:\n');
fprintf('Number of independent boundary segments: %d\n', ...
    length(boundaryPathsLatLon));

geometryFigNum = 30008;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

for iBoundary = 1:length(boundaryPathsLatLon)

    currentBoundary = boundaryPathsLatLon{iBoundary};

    plot( ...
        currentBoundary(:,2), ...
        currentBoundary(:,1), ...
        '.-', ...
        'DisplayName', sprintf('Boundary %d', iBoundary));

end

xlabel('Longitude [deg]');
ylabel('Latitude [deg]');
title('Mapped test-track boundary segments');

% 3. Convert boundary segments from Lat/Lon to ENU

referenceLatitude  = 40.86368573;
referenceLongitude = -77.83592832;
referenceAltitude  = 344.189;

referenceEllipsoid = wgs84Ellipsoid('meter');

boundaryPathsXY = cell(size(boundaryPathsLatLon));

for iBoundary = 1:length(boundaryPathsLatLon)

    currentBoundaryLatLon = boundaryPathsLatLon{iBoundary};

    latitude  = currentBoundaryLatLon(:,1);
    longitude = currentBoundaryLatLon(:,2);
    altitude  = referenceAltitude * ones(size(latitude));

    [xEast, yNorth, ~] = geodetic2enu( ...
        latitude, ...
        longitude, ...
        altitude, ...
        referenceLatitude, ...
        referenceLongitude, ...
        referenceAltitude, ...
        referenceEllipsoid);

    boundaryPathsXY{iBoundary} = [
        xEast, ...
        yNorth
    ];

end

% 4. Plot boundary segments in ENU coordinates

geometryFigNum = 30009;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

for iBoundary = 1:length(boundaryPathsXY)

    currentBoundary = boundaryPathsXY{iBoundary};

    plot( ...
        currentBoundary(:,1), ...
        currentBoundary(:,2), ...
        '.-', ...
        'DisplayName', sprintf('Boundary %d', iBoundary));

end

xlabel('East [m]');
ylabel('North [m]');
title('Mapped test-track boundaries in ENU coordinates');

selectedBoundary = boundaryPathsXY{9};

% 5. Create a predicted path crossing the mapped boundary

predictedPath = [
    200  -170
    200  -150
    200  -130
    200  -110
    200   -90
    200   -70
    200   -50
];


% 6. Plot predicted path and selected mapped boundary

geometryFigNum = 30010;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

plot( ...
    selectedBoundary(:,1), ...
    selectedBoundary(:,2), ...
    '.-', ...
    'LineWidth', 2, ...
    'DisplayName', 'Mapped boundary');

plot( ...
    predictedPath(:,1), ...
    predictedPath(:,2), ...
    '-o', ...
    'LineWidth', 2, ...
    'DisplayName', 'Predicted path');

xlabel('East [m]');
ylabel('North [m]');
title('Predicted path crossing a mapped boundary');
legend('Location','best');

% 7. Compute predictive safety speed profile

boundaryPath = selectedBoundary;

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

figNum = 20008;

[UxDesired, ~, intersectionPoints, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

% 8. Mark braking start and collision station

figure(figNum);
hold on;

if ~isnan(sBrakingStart)
    xline( ...
        sBrakingStart, ...
        '--');
end

xline( ...
    sBrakingStart, ...
    '--', ...
    'HandleVisibility','off');

xline( ...
    sCollision, ...
    ':', ...
    'LineWidth',2, ...
    'HandleVisibility','off');
eventInformation = sprintf( ...
    ['Braking start: %.2f m\n' ...
     'Collision: %.2f m\n' ...
     'Braking distance: %.2f m'], ...
     sBrakingStart, ...
     sCollision, ...
     brakingDistance);

annotation( ...
    'textbox', ...
    [0.68 0.14 0.23 0.13], ...
    'String',eventInformation, ...
    'FitBoxToText','on', ...
    'BackgroundColor','white');

predictedPathStation = [0;
    cumsum(vecnorm(diff(predictedPath),2,2))];

xlim([ ...
    0 ...
    predictedPathStation(end)]);

ylim([ ...
    0, ...
    ceil(1.10 * plannerSettings.U_posted)]);

fprintf('\nMapped-boundary test:\n');
fprintf('Number of intersections: %d\n', ...
    size(intersectionPoints,1));
fprintf('Collision station: %.3f m\n', ...
    sCollision);
fprintf('Braking start: %.3f m\n', ...
    sBrakingStart);
fprintf('Braking distance: %.3f m\n', ...
    brakingDistance);
fprintf('Terminal speed: %.3f m/s\n', ...
    UxDesired(end));

%% BASIC test 9 - Collision too close to stop safely
%
% This test distinguishes between:
%
% 1. The safe-speed limit required to stop at the obstacle.
% 2. The actual predicted vehicle speed when maximum emergency braking is
%    applied from the requested initial speed.
%
% Because the obstacle is too close, the actual predicted speed remains
% greater than zero at the collision station.

% 1. Define a straight predicted path

pathX = ...
    (0:0.1:2)';

predictedPath = [
    pathX, ...
    zeros(size(pathX))
];

% 2. Define an obstacle 0.5 m ahead of the vehicle

boundaryPath = [
    1 -2
    1  2
];

% 3. Define planner settings

muValue = 0.6;
ds = 0.01;

plannerSettings.U_posted   = 5.0;
plannerSettings.U_initial  = 5.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

% Disable internal planner plotting

figNum = [];

% 4. Compute the safe-speed limit and actual predicted speed

[UxDesired, road, intersectionPoints, ...
 sCollision, ~, ~, speedProfileData] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

safeSpeedLimit = ...
    UxDesired;

actualSpeedPredicted = ...
    speedProfileData.U_actual_predicted;

predictedImpactSpeed = ...
    speedProfileData.U_impact_predicted;

isFeasible = ...
    speedProfileData.is_stopping_feasible;

% 5. Calculate analytical reference values for the straight, flat road

availableBrakingAcceleration = ...
    plannerSettings.lambda * ...
    muValue * ...
    plannerSettings.g;

requiredStoppingDistance = ...
    plannerSettings.U_initial^2 / ...
    (2 * availableBrakingAcceleration);

maximumFeasibleInitialSpeed = ...
    safeSpeedLimit(1);

expectedImpactSpeed = sqrt(max( ...
    0, ...
    plannerSettings.U_initial^2 - ...
    2 * availableBrakingAcceleration * ...
    sCollision));

speedReductionBeforeImpact = ...
    plannerSettings.U_initial - ...
    predictedImpactSpeed;

% 6. Plot safe-speed limit and actual predicted speed

speedFigureNumber = 20009;

figure(speedFigureNumber);
clf;
hold on;
grid on;
box on;

safeLimitColor = ...
    [0.4660 0.6740 0.1880];

actualSpeedColor = ...
    [0 0.4470 0.7410];

impactColor = ...
    [0.8500 0.3250 0.0980];

hSafeLimit = plot( ...
    road.s, ...
    safeSpeedLimit, ...
    '-', ...
    'Color', safeLimitColor, ...
    'LineWidth', 2.5, ...
    'DisplayName', 'Safe-speed limit');

hActualSpeed = plot( ...
    road.s, ...
    actualSpeedPredicted, ...
    '-', ...
    'Color', actualSpeedColor, ...
    'LineWidth', 2.5, ...
    'DisplayName', 'Actual predicted speed');

hRequestedSpeed = yline( ...
    plannerSettings.U_initial, ...
    ':', ...
    'Color', [0.4 0.4 0.4], ...
    'LineWidth', 1.5, ...
    'DisplayName', 'Requested initial speed');

hObstacle = xline( ...
    sCollision, ...
    '-', ...
    'Color', [0.25 0.25 0.25], ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

hImpactSpeed = plot( ...
    sCollision, ...
    predictedImpactSpeed, ...
    'x', ...
    'Color', impactColor, ...
    'MarkerSize', 12, ...
    'LineWidth', 3, ...
    'DisplayName', sprintf( ...
        'Predicted impact speed: %.2f m/s', ...
        predictedImpactSpeed));

hRequestedSpeed.Label = '';
hObstacle.Label = '';

xlim([ ...
    0, ...
    sCollision + 0.05]);

ylim([ ...
    0, ...
    1.10 * plannerSettings.U_initial]);

xlabel('Station along path, s [m]');
ylabel('Speed [m/s]');

title( ...
    'Test 9: Infeasible stopping and predicted impact speed');

legend( ...
    [ ...
    hSafeLimit
    hActualSpeed
    hRequestedSpeed
    hObstacle
    hImpactSpeed
    ], ...
    'Location', ...
    'southwest');

currentAxes = gca;
currentAxes.FontSize = 12;
currentAxes.LineWidth = 1;

% 7. Verify the results

tolerance = 1e-3;

assert(~isempty(intersectionPoints), ...
    'An intersection should be detected.');

assert(size(intersectionPoints,1) == 1, ...
    'Exactly one intersection should be detected.');

assert(abs(sCollision - 1.0) < tolerance, ...
    'The collision station should be 1 m.');

assert(abs(safeSpeedLimit(end)) < tolerance, ...
    'The safe-speed limit should reach zero at the obstacle.');

assert(abs( ...
        actualSpeedPredicted(1) - ...
        plannerSettings.U_initial) < tolerance, ...
    ['The actual predicted profile must start from ', ...
     'the requested initial speed.']);

assert(~isFeasible, ...
    'The stopping maneuver should be infeasible.');

assert(predictedImpactSpeed > tolerance, ...
    ['The predicted impact speed should remain greater ', ...
     'than zero.']);

assert(requiredStoppingDistance > sCollision, ...
    ['The required stopping distance should exceed ', ...
     'the available distance.']);

assert(abs( ...
        predictedImpactSpeed - ...
        expectedImpactSpeed) < tolerance, ...
    ['The numerical impact-speed prediction does not ', ...
     'match the analytical straight-road result.']);

assert(all( ...
    actualSpeedPredicted >= ...
    safeSpeedLimit - tolerance), ...
    ['The actual predicted speed should remain above ', ...
     'the safe-speed limit in this infeasible case.']);

% 8. Print results

fprintf('\nBASIC test 9 - Collision too close to stop safely\n');

fprintf('Requested initial speed: %.3f m/s\n', ...
    plannerSettings.U_initial);

fprintf('Maximum feasible initial speed: %.3f m/s\n', ...
    maximumFeasibleInitialSpeed);

fprintf('Available distance to obstacle: %.3f m\n', ...
    sCollision);

fprintf('Required stopping distance: %.3f m\n', ...
    requiredStoppingDistance);

fprintf('Available braking acceleration: %.3f m/s^2\n', ...
    availableBrakingAcceleration);

fprintf('Predicted impact speed: %.3f m/s\n', ...
    predictedImpactSpeed);

fprintf('Analytical impact-speed reference: %.3f m/s\n', ...
    expectedImpactSpeed);

fprintf('Speed reduction before impact: %.3f m/s\n', ...
    speedReductionBeforeImpact);

fprintf('Is stopping maneuver feasible: %d\n', ...
    isFeasible);

%% BASIC test 10 - Gao-based oval trajectory

% Generate the Gao-based oval trajectory
script_VD_reproduceGaoChapter5Figs

% Save the generated centerline
gaoRoad = road;

% Close figures generated internally by the Gao reproduction script
close(21001);
close(21002);
close(21003);
close(21004);

predictedPath = [
    gaoRoad.x, ...
    gaoRoad.y
];

% Boundary placed away from the initial path point
boundaryX = 300;

boundaryPath = [
    boundaryX, min(predictedPath(:,2)) - 50
    boundaryX, max(predictedPath(:,2)) + 50
];
% Planner settings

muValue = 0.6;
ds = 1;

plannerSettings.U_posted   = 15.0;
plannerSettings.U_initial  = 15.0;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

figNum = 20010;

% Compute predictive safety speed profile

[UxDesired, plannerRoad, intersectionPoints, ...
 sCollision, sBrakingStart, brakingDistance, ...
 ~] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPath, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        figNum);

% Plot trajectory and detected intersections

geometryFigNum = 30011;

figure(geometryFigNum);
clf;
hold on;
grid on;
axis equal;

plot( ...
    predictedPath(:,1), ...
    predictedPath(:,2), ...
    '-', ...
    'LineWidth', 2, ...
    'DisplayName', 'Gao-based predicted path');

plot( ...
    boundaryPath(:,1), ...
    boundaryPath(:,2), ...
    '--', ...
    'LineWidth', 2, ...
    'DisplayName', 'Artificial boundary');

plot( ...
    intersectionPoints(:,1), ...
    intersectionPoints(:,2), ...
    'x', ...
    'MarkerSize', 12, ...
    'LineWidth', 2, ...
    'DisplayName', 'Intersections');

xlabel('East [m]');
ylabel('North [m]');
title('Gao-based oval trajectory and artificial boundary');
legend('Location','best');

% Mark braking start and first collision

figure(figNum);
hold on;

if ~isnan(sBrakingStart)

    xline( ...
        sBrakingStart, ...
        '--', ...
        'LineWidth', ...
        1.5, ...
        'HandleVisibility', ...
        'off');

end

xline( ...
    sCollision, ...
    ':', ...
    'LineWidth', ...
    2, ...
    'HandleVisibility', ...
    'off');

% Adjust plot limits

xMargin = max(5, 0.05*sCollision);

xlim([ ...
    0, ...
    sCollision + xMargin]);

ylim([ ...
    0, ...
    ceil(1.10 * plannerSettings.U_posted)]);

xlabel('Station along predicted path [m]');
ylabel('Speed [m/s]');

% Display event information in the lower-right corner

eventInformation = sprintf( ...
    ['Braking start: %.2f m\n' ...
     'First collision: %.2f m\n' ...
     'Braking distance: %.2f m'], ...
     sBrakingStart, ...
     sCollision, ...
     brakingDistance);

annotation( ...
    'textbox', ...
    [0.68 0.14 0.23 0.13], ...
    'String', ...
    eventInformation, ...
    'FitBoxToText', ...
    'on', ...
    'BackgroundColor', ...
    'white');

% Checks

assert(~isempty(intersectionPoints), ...
    'At least one intersection should be detected.');

assert(~isnan(sCollision), ...
    'The first collision station should be defined.');

assert(abs(UxDesired(end)) < 1e-6, ...
    'Terminal speed should be zero.');

assert(abs(plannerRoad.s(end) - sCollision) < ds + 1e-6, ...
    'The planner road should end at the first collision station.');

%% BASIC test 11 - CW versus CCW stopping at the same physical obstacle
%
% This test uses the complete mapped Test Track boundaries to generate an
% approximate center path.
%
% A physical obstacle is positioned automatically at a location where the
% curvature during the clockwise approach is greater than the curvature
% during the counter-clockwise approach.
%
% The same physical obstacle, friction coefficient, initial speed and
% planner settings are used in both directions.
%
% The test compares:
%
% - Braking distance.
% - Safe speed profile.
% - Longitudinal acceleration.
% - Lateral acceleration.
% - Friction allocation.
%
% The obstacle station is shifted to s_relative = 0 in the comparison
% figures.

% 1. Locate and load the Test Track boundary data

currentFilePath = which( ...
    'script_test_fcn_VD_computePredictiveSafetySpeedProfile.m');

[currentFolder, ~, ~] = ...
    fileparts(currentFilePath);

repoRoot = fullfile( ...
    currentFolder, ...
    '..', ...
    '..');

dataFolder = fullfile( ...
    repoRoot, ...
    'Data');

dataFile = fullfile( ...
    dataFolder, ...
    'testTrackBoundariesXY.mat');

fprintf('\nLoading Test Track boundaries from:\n%s\n', ...
    dataFile);

assert(isfile(dataFile), ...
    'The Test Track boundary data file could not be found.');

loadedData = load(dataFile);

assert(isfield(loadedData, 'outerBoundaryXY'), ...
    'The data file must contain outerBoundaryXY.');

assert(isfield(loadedData, 'innerBoundaryXY'), ...
    'The data file must contain innerBoundaryXY.');

outerBoundaryXY = ...
    loadedData.outerBoundaryXY;

innerBoundaryXY = ...
    loadedData.innerBoundaryXY;

assert(size(outerBoundaryXY,2) == 2, ...
    'outerBoundaryXY must be an N-by-2 matrix.');

assert(size(innerBoundaryXY,2) == 2, ...
    'innerBoundaryXY must be an N-by-2 matrix.');

% 2. Remove invalid rows

outerBoundaryXY = outerBoundaryXY( ...
    ~any(isnan(outerBoundaryXY),2), :);

innerBoundaryXY = innerBoundaryXY( ...
    ~any(isnan(innerBoundaryXY),2), :);

assert(size(outerBoundaryXY,1) >= 3, ...
    'The outer boundary must contain at least three valid points.');

assert(size(innerBoundaryXY,1) >= 3, ...
    'The inner boundary must contain at least three valid points.');

% 3. Remove repeated closing points temporarily

closureTolerance = 1e-6;

if norm( ...
        outerBoundaryXY(end,:) - ...
        outerBoundaryXY(1,:)) < closureTolerance

    outerBoundaryXY = ...
        outerBoundaryXY(1:end-1,:);

end

if norm( ...
        innerBoundaryXY(end,:) - ...
        innerBoundaryXY(1,:)) < closureTolerance

    innerBoundaryXY = ...
        innerBoundaryXY(1:end-1,:);

end

% 4. Ensure that the two boundaries follow the same direction

outerClosedForArea = [
    outerBoundaryXY
    outerBoundaryXY(1,:)
];

innerClosedForArea = [
    innerBoundaryXY
    innerBoundaryXY(1,:)
];

outerSignedArea = 0.5 * sum( ...
    outerClosedForArea(1:end-1,1) .* ...
    outerClosedForArea(2:end,2) - ...
    outerClosedForArea(2:end,1) .* ...
    outerClosedForArea(1:end-1,2));

innerSignedArea = 0.5 * sum( ...
    innerClosedForArea(1:end-1,1) .* ...
    innerClosedForArea(2:end,2) - ...
    innerClosedForArea(2:end,1) .* ...
    innerClosedForArea(1:end-1,2));

if sign(outerSignedArea) ~= sign(innerSignedArea)

    innerBoundaryXY = ...
        flipud(innerBoundaryXY);

end

% 5. Align the starting points of the boundaries

distanceToOuterStart = sqrt(sum( ...
    (innerBoundaryXY - outerBoundaryXY(1,:)).^2, ...
    2));

[~, closestInnerStartIndex] = ...
    min(distanceToOuterStart);

innerBoundaryXY = [
    innerBoundaryXY(closestInnerStartIndex:end,:)
    innerBoundaryXY(1:closestInnerStartIndex-1,:)
];

% 6. Close the original boundaries

outerBoundaryClosed = [
    outerBoundaryXY
    outerBoundaryXY(1,:)
];

innerBoundaryClosed = [
    innerBoundaryXY
    innerBoundaryXY(1,:)
];

% 7. Calculate normalized station along each boundary

outerSegmentVectors = diff( ...
    outerBoundaryClosed, ...
    1, ...
    1);

outerSegmentLengths = sqrt(sum( ...
    outerSegmentVectors.^2, ...
    2));

outerStation = [
    0
    cumsum(outerSegmentLengths)
];

assert(outerStation(end) > 0, ...
    'The outer boundary must have a positive total length.');

outerNormalizedStation = ...
    outerStation ./ outerStation(end);

innerSegmentVectors = diff( ...
    innerBoundaryClosed, ...
    1, ...
    1);

innerSegmentLengths = sqrt(sum( ...
    innerSegmentVectors.^2, ...
    2));

innerStation = [
    0
    cumsum(innerSegmentLengths)
];

assert(innerStation(end) > 0, ...
    'The inner boundary must have a positive total length.');

innerNormalizedStation = ...
    innerStation ./ innerStation(end);

% 8. Resample both boundaries
%
% A relatively fine center-path discretization is used so that path
% smoothing does not remove the relevant curve geometry.

numberOfCenterPathPoints = 1200;

commonNormalizedStation = linspace( ...
    0, ...
    1, ...
    numberOfCenterPathPoints + 1)';

outerBoundaryResampledClosed = [
    interp1( ...
        outerNormalizedStation, ...
        outerBoundaryClosed(:,1), ...
        commonNormalizedStation, ...
        'linear'), ...
    interp1( ...
        outerNormalizedStation, ...
        outerBoundaryClosed(:,2), ...
        commonNormalizedStation, ...
        'linear')
];

innerBoundaryResampledClosed = [
    interp1( ...
        innerNormalizedStation, ...
        innerBoundaryClosed(:,1), ...
        commonNormalizedStation, ...
        'linear'), ...
    interp1( ...
        innerNormalizedStation, ...
        innerBoundaryClosed(:,2), ...
        commonNormalizedStation, ...
        'linear')
];

% 9. Generate the center path

centerPathCandidateClosed = 0.5 .* ( ...
    outerBoundaryResampledClosed + ...
    innerBoundaryResampledClosed);

centerPathCandidate = ...
    centerPathCandidateClosed(1:end-1,:);

outerBoundaryResampled = ...
    outerBoundaryResampledClosed(1:end-1,:);

innerBoundaryResampled = ...
    innerBoundaryResampledClosed(1:end-1,:);

assert(size(centerPathCandidate,1) >= 5, ...
    'The generated center path must contain at least five points.');

% 10. Normalize the center-path direction
%
% Positive signed area corresponds to a counter-clockwise point ordering.
% The path is normalized so that predictedPathCCW is always CCW.

centerPathCandidateClosed = [
    centerPathCandidate
    centerPathCandidate(1,:)
];

centerPathSignedArea = 0.5 * sum( ...
    centerPathCandidateClosed(1:end-1,1) .* ...
    centerPathCandidateClosed(2:end,2) - ...
    centerPathCandidateClosed(2:end,1) .* ...
    centerPathCandidateClosed(1:end-1,2));

if centerPathSignedArea < 0

    centerPathCandidate = ...
        flipud(centerPathCandidate);

    outerBoundaryResampled = ...
        flipud(outerBoundaryResampled);

    innerBoundaryResampled = ...
        flipud(innerBoundaryResampled);

end

predictedPathCCW = ...
    centerPathCandidate;

predictedPathCW = ...
    flipud(predictedPathCCW);

centerPathClosed = [
    predictedPathCCW
    predictedPathCCW(1,:)
];

% 11. Define planner settings
%
% Use 15.0 m/s to reproduce the previous test.
% Use 18.0 m/s to make the friction-allocation effect more visible.

comparisonSpeed = 20.0;

muValue = 0.6;
ds = 0.1;

plannerSettings.U_posted   = comparisonSpeed;
plannerSettings.U_initial  = comparisonSpeed;
plannerSettings.U_terminal = 0.0;
plannerSettings.lambda     = 0.9;
plannerSettings.g          = 9.81;

availableFrictionAcceleration = ...
    plannerSettings.lambda * ...
    muValue * ...
    plannerSettings.g;

referenceBrakingDistance = ...
    comparisonSpeed^2 / ...
    (2 * availableFrictionAcceleration);

% 12. Calculate periodic center-path curvature

numberOfPathPoints = ...
    size(predictedPathCCW,1);

closedCenterPathForSegments = [
    predictedPathCCW
    predictedPathCCW(1,:)
];

centerSegmentVectors = diff( ...
    closedCenterPathForSegments, ...
    1, ...
    1);

centerSegmentLengths = sqrt(sum( ...
    centerSegmentVectors.^2, ...
    2));

centerPathLength = ...
    sum(centerSegmentLengths);

assert(centerPathLength > 0, ...
    'The generated center path must have positive length.');

centerPathStation = [
    0
    cumsum(centerSegmentLengths(1:end-1))
];

previousPointIndices = [
    numberOfPathPoints
    (1:numberOfPathPoints-1)'
];

nextPointIndices = [
    (2:numberOfPathPoints)'
    1
];

incomingVectors = ...
    predictedPathCCW - ...
    predictedPathCCW(previousPointIndices,:);

outgoingVectors = ...
    predictedPathCCW(nextPointIndices,:) - ...
    predictedPathCCW;

signedCrossProducts = ...
    incomingVectors(:,1) .* outgoingVectors(:,2) - ...
    incomingVectors(:,2) .* outgoingVectors(:,1);

directionDotProducts = sum( ...
    incomingVectors .* outgoingVectors, ...
    2);

signedTurningAngles = atan2( ...
    signedCrossProducts, ...
    directionDotProducts);

incomingLengths = sqrt(sum( ...
    incomingVectors.^2, ...
    2));

outgoingLengths = sqrt(sum( ...
    outgoingVectors.^2, ...
    2));

localArcLengths = ...
    0.5 * (incomingLengths + outgoingLengths);

localArcLengths = max( ...
    localArcLengths, ...
    1e-6);

rawAbsoluteCurvature = ...
    abs(signedTurningAngles) ./ ...
    localArcLengths;

% 13. Smooth the periodic curvature signal
%
% The smoothing window is defined using a physical distance rather than a
% fixed number of path samples.

meanCenterPointSpacing = ...
    centerPathLength / numberOfPathPoints;

curvatureSmoothingDistance = 8.0;

curvatureSmoothingPoints = max( ...
    5, ...
    round( ...
        curvatureSmoothingDistance / ...
        meanCenterPointSpacing));

if mod(curvatureSmoothingPoints,2) == 0

    curvatureSmoothingPoints = ...
        curvatureSmoothingPoints + 1;

end

extendedCurvature = [
    rawAbsoluteCurvature
    rawAbsoluteCurvature
    rawAbsoluteCurvature
];

extendedCurvature = smoothdata( ...
    extendedCurvature, ...
    'movmedian', ...
    curvatureSmoothingPoints);

extendedCurvature = smoothdata( ...
    extendedCurvature, ...
    'movmean', ...
    curvatureSmoothingPoints);

absoluteCenterPathCurvature = ...
    extendedCurvature( ...
        numberOfPathPoints+1: ...
        2*numberOfPathPoints);

% 14. Calculate point-integration weights

previousSegmentLengths = [
    centerSegmentLengths(end)
    centerSegmentLengths(1:end-1)
];

pointIntegrationWeights = ...
    0.5 * ( ...
        previousSegmentLengths + ...
        centerSegmentLengths);

% 15. Select an obstacle position
%
% For a candidate obstacle:
%
% - The CCW approach consists of points behind the candidate in the current
%   CCW path ordering.
%
% - The CW approach consists of points ahead of the candidate in the
%   current CCW ordering.
%
% Weighted RMS curvature is used because lateral demand is directly related
% to curvature and enters quadratically in the friction-circle constraint.

rmsApproachCurvatureCCW = ...
    NaN(numberOfPathPoints,1);

rmsApproachCurvatureCW = ...
    NaN(numberOfPathPoints,1);

meanApproachCurvatureCCW = ...
    NaN(numberOfPathPoints,1);

meanApproachCurvatureCW = ...
    NaN(numberOfPathPoints,1);

for iCandidate = 1:numberOfPathPoints

    distanceBehindCandidate = mod( ...
        centerPathStation(iCandidate) - ...
        centerPathStation, ...
        centerPathLength);

    distanceAheadOfCandidate = mod( ...
        centerPathStation - ...
        centerPathStation(iCandidate), ...
        centerPathLength);

    ccwApproachMask = ...
        distanceBehindCandidate > 0 & ...
        distanceBehindCandidate <= ...
        referenceBrakingDistance;

    cwApproachMask = ...
        distanceAheadOfCandidate > 0 & ...
        distanceAheadOfCandidate <= ...
        referenceBrakingDistance;

    if any(ccwApproachMask)

        ccwWeights = ...
            pointIntegrationWeights(ccwApproachMask);

        ccwCurvature = ...
            absoluteCenterPathCurvature(ccwApproachMask);

        meanApproachCurvatureCCW(iCandidate) = ...
            sum(ccwCurvature .* ccwWeights) / ...
            sum(ccwWeights);

        rmsApproachCurvatureCCW(iCandidate) = sqrt( ...
            sum(ccwCurvature.^2 .* ccwWeights) / ...
            sum(ccwWeights));

    end

    if any(cwApproachMask)

        cwWeights = ...
            pointIntegrationWeights(cwApproachMask);

        cwCurvature = ...
            absoluteCenterPathCurvature(cwApproachMask);

        meanApproachCurvatureCW(iCandidate) = ...
            sum(cwCurvature .* cwWeights) / ...
            sum(cwWeights);

        rmsApproachCurvatureCW(iCandidate) = sqrt( ...
            sum(cwCurvature.^2 .* cwWeights) / ...
            sum(cwWeights));

    end

end

% 16. Exclude candidate locations too close to the path-array seam

minimumAvailablePathBeforeObstacle = ...
    referenceBrakingDistance + 10;

distanceFromCCWStart = ...
    centerPathStation;

distanceFromCWStart = ...
    centerPathLength - centerPathStation;

candidateValidityMask = ...
    distanceFromCCWStart >= ...
        minimumAvailablePathBeforeObstacle & ...
    distanceFromCWStart >= ...
        minimumAvailablePathBeforeObstacle;

localTrackWidths = sqrt(sum( ...
    (outerBoundaryResampled - ...
     innerBoundaryResampled).^2, ...
    2));

candidateValidityMask = ...
    candidateValidityMask & ...
    localTrackWidths > 1;

directionalCurvatureContrast = ...
    rmsApproachCurvatureCW - ...
    rmsApproachCurvatureCCW;

directionalCurvatureContrast( ...
    ~candidateValidityMask) = NaN;

[maximumDirectionalCurvatureContrast, ...
 obstaclePathIndex] = max( ...
    directionalCurvatureContrast, ...
    [], ...
    'omitnan');

assert(~isnan(maximumDirectionalCurvatureContrast), ...
    ['A valid obstacle location based on directional ', ...
     'curvature contrast could not be identified.']);

assert(maximumDirectionalCurvatureContrast > 0, ...
    ['The selected location does not produce greater ', ...
     'clockwise approach curvature.']);

obstacleCenter = ...
    predictedPathCCW(obstaclePathIndex,:);

% 17. Calculate obstacle orientation

previousObstacleIndex = mod( ...
    obstaclePathIndex - 2, ...
    numberOfPathPoints) + 1;

nextObstacleIndex = mod( ...
    obstaclePathIndex, ...
    numberOfPathPoints) + 1;

localTangent = ...
    predictedPathCCW(nextObstacleIndex,:) - ...
    predictedPathCCW(previousObstacleIndex,:);

localTangentNorm = ...
    norm(localTangent);

assert(localTangentNorm > 0, ...
    'The local path tangent must have non-zero magnitude.');

localTangent = ...
    localTangent ./ localTangentNorm;

localNormal = [
    -localTangent(2), ...
     localTangent(1)
];

% 18. Determine obstacle length

localTrackWidth = ...
    localTrackWidths(obstaclePathIndex);

assert(localTrackWidth > 0, ...
    'The estimated local track width must be positive.');

obstacleLength = ...
    0.60 * localTrackWidth;

obstaclePath = [
    obstacleCenter - ...
    0.5 * obstacleLength * localNormal

    obstacleCenter + ...
    0.5 * obstacleLength * localNormal
];

boundaryPath = ...
    obstaclePath;

% 19. Compute the counter-clockwise speed profile

[UxDesiredCCW, roadCCW, intersectionPointsCCW, ...
 sCollisionCCW, functionSBrakingStartCCW, ...
 functionBrakingDistanceCCW, speedProfileDataCCW] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPathCCW, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        []);

% 20. Identify obstacle-related CCW braking start

tolerance = 1e-3;

nonObstacleSpeedLimitCCW = min( ...
    speedProfileDataCCW.U_forward, ...
    speedProfileDataCCW.U_corner);

obstacleBrakingIndexCCW = find( ...
    speedProfileDataCCW.U_backward < ...
    nonObstacleSpeedLimitCCW - tolerance, ...
    1, ...
    'first');

assert(~isempty(obstacleBrakingIndexCCW), ...
    'The CCW obstacle braking region could not be identified.');

sBrakingStartCCW = ...
    roadCCW.s(obstacleBrakingIndexCCW);

brakingDistanceCCW = ...
    sCollisionCCW - sBrakingStartCCW;

% 21. Compute the clockwise speed profile

[UxDesiredCW, roadCW, intersectionPointsCW, ...
 sCollisionCW, functionSBrakingStartCW, ...
 functionBrakingDistanceCW, speedProfileDataCW] = ...
    fcn_VD_computePredictiveSafetySpeedProfile( ...
        predictedPathCW, ...
        boundaryPath, ...
        muValue, ...
        plannerSettings, ...
        ds, ...
        []);

% 22. Identify obstacle-related CW braking start

nonObstacleSpeedLimitCW = min( ...
    speedProfileDataCW.U_forward, ...
    speedProfileDataCW.U_corner);

obstacleBrakingIndexCW = find( ...
    speedProfileDataCW.U_backward < ...
    nonObstacleSpeedLimitCW - tolerance, ...
    1, ...
    'first');

assert(~isempty(obstacleBrakingIndexCW), ...
    'The CW obstacle braking region could not be identified.');

sBrakingStartCW = ...
    roadCW.s(obstacleBrakingIndexCW);

brakingDistanceCW = ...
    sCollisionCW - sBrakingStartCW;

% 23. Define station relative to the obstacle

relativeStationCCW = ...
    roadCCW.s - sCollisionCCW;

relativeStationCW = ...
    roadCW.s - sCollisionCW;

relativeBrakingStartCCW = ...
    sBrakingStartCCW - sCollisionCCW;

relativeBrakingStartCW = ...
    sBrakingStartCW - sCollisionCW;

% 24. Define braking-region masks

brakingRegionMaskCCW = ...
    roadCCW.s >= sBrakingStartCCW & ...
    roadCCW.s <= sCollisionCCW;

brakingRegionMaskCW = ...
    roadCW.s >= sBrakingStartCW & ...
    roadCW.s <= sCollisionCW;

% 25. Calculate acceleration and curvature metrics

combinedAccelerationCCW = sqrt( ...
    speedProfileDataCCW.a_x.^2 + ...
    speedProfileDataCCW.a_y.^2);

combinedAccelerationCW = sqrt( ...
    speedProfileDataCW.a_x.^2 + ...
    speedProfileDataCW.a_y.^2);

maximumLateralAccelerationCCW = max( ...
    abs(speedProfileDataCCW.a_y( ...
        brakingRegionMaskCCW)), ...
    [], ...
    'omitnan');

maximumLateralAccelerationCW = max( ...
    abs(speedProfileDataCW.a_y( ...
        brakingRegionMaskCW)), ...
    [], ...
    'omitnan');

meanLateralAccelerationCCW = mean( ...
    abs(speedProfileDataCCW.a_y( ...
        brakingRegionMaskCCW)), ...
    'omitnan');

meanLateralAccelerationCW = mean( ...
    abs(speedProfileDataCW.a_y( ...
        brakingRegionMaskCW)), ...
    'omitnan');

maximumLongitudinalAccelerationCCW = max( ...
    abs(speedProfileDataCCW.a_x( ...
        brakingRegionMaskCCW)), ...
    [], ...
    'omitnan');

maximumLongitudinalAccelerationCW = max( ...
    abs(speedProfileDataCW.a_x( ...
        brakingRegionMaskCW)), ...
    [], ...
    'omitnan');

meanBrakingCurvatureCCW = mean( ...
    abs(roadCCW.kappa(brakingRegionMaskCCW)), ...
    'omitnan');

meanBrakingCurvatureCW = mean( ...
    abs(roadCW.kappa(brakingRegionMaskCW)), ...
    'omitnan');

maximumBrakingCurvatureCCW = max( ...
    abs(roadCCW.kappa(brakingRegionMaskCCW)), ...
    [], ...
    'omitnan');

maximumBrakingCurvatureCW = max( ...
    abs(roadCW.kappa(brakingRegionMaskCW)), ...
    [], ...
    'omitnan');

maximumCombinedAccelerationCCW = max( ...
    combinedAccelerationCCW(brakingRegionMaskCCW), ...
    [], ...
    'omitnan');

maximumCombinedAccelerationCW = max( ...
    combinedAccelerationCW(brakingRegionMaskCW), ...
    [], ...
    'omitnan');

maximumLateralFrictionUseCCW = ...
    maximumLateralAccelerationCCW / ...
    availableFrictionAcceleration;

maximumLateralFrictionUseCW = ...
    maximumLateralAccelerationCW / ...
    availableFrictionAcceleration;

meanLateralFrictionUseCCW = ...
    meanLateralAccelerationCCW / ...
    availableFrictionAcceleration;

meanLateralFrictionUseCW = ...
    meanLateralAccelerationCW / ...
    availableFrictionAcceleration;

brakingDistanceDifference = ...
    brakingDistanceCW - brakingDistanceCCW;

brakingDistancePercentageDifference = ...
    100 * brakingDistanceDifference / ...
    brakingDistanceCCW;

% 27. Plot the mapped track and fixed physical obstacle

geometryFigNum = 30012;

figure(geometryFigNum);
clf;
hold on;
grid on;
box on;
axis equal;

plot( ...
    outerBoundaryClosed(:,1), ...
    outerBoundaryClosed(:,2), ...
    '-', ...
    'LineWidth', 0.8, ...
    'DisplayName', 'Outer boundary');

plot( ...
    innerBoundaryClosed(:,1), ...
    innerBoundaryClosed(:,2), ...
    '-', ...
    'LineWidth', 0.8, ...
    'DisplayName', 'Inner boundary');

plot( ...
    centerPathClosed(:,1), ...
    centerPathClosed(:,2), ...
    '--', ...
    'LineWidth', 2, ...
    'DisplayName', 'Generated center path');

plot( ...
    obstaclePath(:,1), ...
    obstaclePath(:,2), ...
    '-', ...
    'LineWidth', 4, ...
    'DisplayName', 'Fixed physical obstacle');

plot( ...
    intersectionPointsCCW(:,1), ...
    intersectionPointsCCW(:,2), ...
    'x', ...
    'MarkerSize', 13, ...
    'LineWidth', 3, ...
    'DisplayName', 'Detected intersection');

xlabel('East [m]');
ylabel('North [m]');

title( ...
    'Mapped Test Track with fixed physical obstacle');

legend( ...
    'Location', ...
    'best');

% 28. Plot the CW and CCW stopping profiles

speedComparisonFigNum = 30016;

figure(speedComparisonFigNum);
clf;
hold on;
grid on;
box on;

hSpeedCCW = plot( ...
    relativeStationCCW, ...
    UxDesiredCCW, ...
    'LineWidth', 2.5, ...
    'DisplayName', sprintf( ...
        'CCW: braking distance %.2f m', ...
        brakingDistanceCCW));

hSpeedCW = plot( ...
    relativeStationCW, ...
    UxDesiredCW, ...
    '-', ...
    'LineWidth', 2.5, ...
    'DisplayName', sprintf( ...
        'CW: braking distance %.2f m', ...
        brakingDistanceCW));

hBrakingCCW = xline( ...
    relativeBrakingStartCCW, ...
    ':', ...
    'LineWidth', 1.8, ...
    'DisplayName', 'CCW braking start');

hBrakingCW = xline( ...
    relativeBrakingStartCW, ...
    '-.', ...
    'LineWidth', 1.8, ...
    'DisplayName', 'CW braking start');

hObstacle = xline( ...
    0, ...
    '-', ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

hPostedSpeed = yline( ...
    comparisonSpeed, ...
    ':', ...
    'LineWidth', 1.4, ...
    'DisplayName', 'Posted speed');

hBrakingCCW.Label = '';
hBrakingCW.Label = '';
hObstacle.Label = '';
hPostedSpeed.Label = '';

comparisonPlotDistance = max([ ...
    brakingDistanceCCW
    brakingDistanceCW
    referenceBrakingDistance
]);

xlim([ ...
    -comparisonPlotDistance - 10, ...
    3]);

ylim([ ...
    0, ...
    1.08 * comparisonSpeed]);

xlabel('Station relative to obstacle [m]');
ylabel('Safe speed [m/s]');

title( ...
    'CW and CCW stopping profiles at the same physical obstacle');

legend( ...
    [ ...
    hSpeedCCW
    hSpeedCW
    hBrakingCCW
    hBrakingCW
    hObstacle
    hPostedSpeed
    ], ...
    'Location', ...
    'best');

currentAxes = gca;
currentAxes.FontSize = 12;
currentAxes.LineWidth = 1;

% 29. Plot curvature before the obstacle

curvatureComparisonFigNum = 30015;

figure(curvatureComparisonFigNum);
clf;
hold on;
grid on;
box on;

ccwColor = [0 0.4470 0.7410];
cwColor  = [0.8500 0.3250 0.0980];

plot( ...
    relativeStationCCW, ...
    abs(roadCCW.kappa), ...
    '-', ...
    'Color', ccwColor, ...
    'LineWidth', 2.2, ...
    'DisplayName', 'CCW absolute curvature');

plot( ...
    relativeStationCW, ...
    abs(roadCW.kappa), ...
    '-', ...
    'Color', cwColor, ...
    'LineWidth', 2.2, ...
    'DisplayName', 'CW absolute curvature');

xline( ...
    relativeBrakingStartCCW, ...
    ':', ...
    'Color', ccwColor, ...
    'LineWidth', 1.5, ...
    'DisplayName', 'CCW braking start');

xline( ...
    relativeBrakingStartCW, ...
    ':', ...
    'Color', cwColor, ...
    'LineWidth', 1.5, ...
    'DisplayName', 'CW braking start');

xline( ...
    0, ...
    '-', ...
    'Color', [0.25 0.25 0.25], ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

xlim([ ...
    -comparisonPlotDistance - 10, ...
    3]);

xlabel('Station relative to obstacle [m]');
ylabel('Absolute curvature [1/m]');

title( ...
    'Path curvature during the CW and CCW approaches');

legend( ...
    'Location', ...
    'best');

% 30. Plot longitudinal and lateral friction use

frictionComparisonFigNum = 30017;

figure(frictionComparisonFigNum);
clf;
hold on;
grid on;
box on;

ccwColor = [0 0.4470 0.7410];
cwColor  = [0.8500 0.3250 0.0980];

% CCW longitudinal acceleration
plot( ...
    relativeStationCCW, ...
    abs(speedProfileDataCCW.a_x), ...
    '-', ...
    'Color', ccwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CCW longitudinal acceleration');

% CW longitudinal acceleration
plot( ...
    relativeStationCW, ...
    abs(speedProfileDataCW.a_x), ...
    '-', ...
    'Color', cwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CW longitudinal acceleration');

% CCW lateral acceleration
plot( ...
    relativeStationCCW, ...
    abs(speedProfileDataCCW.a_y), ...
    '--', ...
    'Color', ccwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CCW lateral acceleration');

% CW lateral acceleration
plot( ...
    relativeStationCW, ...
    abs(speedProfileDataCW.a_y), ...
    '--', ...
    'Color', cwColor, ...
    'LineWidth', 2, ...
    'DisplayName', 'CW lateral acceleration');

yline( ...
    availableFrictionAcceleration, ...
    ':', ...
    'Color', [0.4 0.4 0.4], ...
    'LineWidth', 2, ...
    'DisplayName', 'Available friction acceleration');

xline( ...
    0, ...
    '-', ...
    'Color', [0.25 0.25 0.25], ...
    'LineWidth', 2, ...
    'DisplayName', 'Obstacle');

xlim([ ...
    -comparisonPlotDistance - 10, ...
    3]);

ylim([ ...
    0, ...
    1.10 * availableFrictionAcceleration]);

xlabel('Station relative to obstacle [m]');
ylabel('Acceleration magnitude [m/s^2]');

title( ...
    'Longitudinal and lateral friction use before the obstacle');

legend( ...
    'Location', ...
    'best');
% 31. Verify intersections and terminal conditions

assert(~isempty(intersectionPointsCCW), ...
    'The CCW path should intersect the obstacle.');

assert(~isempty(intersectionPointsCW), ...
    'The CW path should intersect the obstacle.');

assert(size(intersectionPointsCCW,1) == 1, ...
    'The CCW path should have exactly one intersection.');

assert(size(intersectionPointsCW,1) == 1, ...
    'The CW path should have exactly one intersection.');

assert(abs(UxDesiredCCW(end)) < 1e-6, ...
    'The CCW profile must reach zero speed at the obstacle.');

assert(abs(UxDesiredCW(end)) < 1e-6, ...
    'The CW profile must reach zero speed at the obstacle.');

assert(abs(roadCCW.s(end) - sCollisionCCW) < ds + 1e-6, ...
    ['The CCW planner road must terminate at the ', ...
     'obstacle station.']);

assert(abs(roadCW.s(end) - sCollisionCW) < ds + 1e-6, ...
    ['The CW planner road must terminate at the ', ...
     'obstacle station.']);

obstacleIntersectionTolerance = max( ...
    ds, ...
    0.05 * obstacleLength);

intersectionLocationDifference = norm( ...
    intersectionPointsCW(1,:) - ...
    intersectionPointsCCW(1,:));

assert( ...
    intersectionLocationDifference <= ...
    obstacleIntersectionTolerance, ...
    ['Both directions must detect the same physical ', ...
     'obstacle location.']);

assert(all(isfinite(UxDesiredCCW)), ...
    'The CCW speed profile contains invalid values.');

assert(all(isfinite(UxDesiredCW)), ...
    'The CW speed profile contains invalid values.');

% Verify compliance with the friction-circle constraint

frictionVerificationTolerance = ...
    1e-6 * max( ...
        1, ...
        availableFrictionAcceleration);

assert( ...
    all(combinedAccelerationCCW <= ...
        availableFrictionAcceleration + ...
        frictionVerificationTolerance), ...
    ['The CCW speed profile violates the ', ...
     'available friction limit.']);

assert( ...
    all(combinedAccelerationCW <= ...
        availableFrictionAcceleration + ...
        frictionVerificationTolerance), ...
    ['The CW speed profile violates the ', ...
     'available friction limit.']);

% Verify that the comparison speed is below the uncapped physical
% cornering-speed limit throughout the relevant approach region
%
% speedProfileData.U_corner cannot be used for this verification because
% it is capped internally at U_posted. The uncapped lateral cornering limit
% is therefore calculated directly from curvature and friction.

cornerCheckDistance = ...
    max([ ...
        brakingDistanceCCW, ...
        brakingDistanceCW]) + 5;

cornerCheckMaskCCW = ...
    relativeStationCCW >= -cornerCheckDistance & ...
    relativeStationCCW <= 0;

cornerCheckMaskCW = ...
    relativeStationCW >= -cornerCheckDistance & ...
    relativeStationCW <= 0;

assert(any(cornerCheckMaskCCW), ...
    'The CCW cornering-speed check region is empty.');

assert(any(cornerCheckMaskCW), ...
    'The CW cornering-speed check region is empty.');

kappaFloor = 1e-12;

uncappedCornerSpeedCCW = ...
    inf(size(roadCCW.kappa));

uncappedCornerSpeedCW = ...
    inf(size(roadCW.kappa));

curvedRoadMaskCCW = ...
    abs(roadCCW.kappa) > kappaFloor;

curvedRoadMaskCW = ...
    abs(roadCW.kappa) > kappaFloor;

uncappedCornerSpeedCCW(curvedRoadMaskCCW) = sqrt( ...
    availableFrictionAcceleration ./ ...
    abs(roadCCW.kappa(curvedRoadMaskCCW)));

uncappedCornerSpeedCW(curvedRoadMaskCW) = sqrt( ...
    availableFrictionAcceleration ./ ...
    abs(roadCW.kappa(curvedRoadMaskCW)));

minimumCornerSpeedCCW = min( ...
    uncappedCornerSpeedCCW(cornerCheckMaskCCW), ...
    [], ...
    'omitnan');

minimumCornerSpeedCW = min( ...
    uncappedCornerSpeedCW(cornerCheckMaskCW), ...
    [], ...
    'omitnan');

minimumPhysicalCornerSpeed = min( ...
    minimumCornerSpeedCCW, ...
    minimumCornerSpeedCW);

cornerSpeedMargin = ...
    minimumPhysicalCornerSpeed - comparisonSpeed;

cornerSpeedVerificationTolerance = 1e-6;

assert( ...
    cornerSpeedMargin > cornerSpeedVerificationTolerance, ...
    ['The selected comparison speed reaches or exceeds ', ...
     'the uncapped physical cornering-speed limit in the ', ...
     'analyzed approach region.']);

% 32. Report the obstacle-selection results

fprintf('\nBASIC test 11 - CW versus CCW comparison\n');

fprintf('\nPlanner settings:\n');

fprintf('Comparison speed: %.3f m/s\n', ...
    comparisonSpeed);

fprintf('Friction coefficient: %.3f\n', ...
    muValue);

fprintf('Friction margin lambda: %.3f\n', ...
    plannerSettings.lambda);

fprintf('Available friction acceleration: %.3f m/s^2\n', ...
    availableFrictionAcceleration);

fprintf('Straight-road reference braking distance: %.3f m\n', ...
    referenceBrakingDistance);

fprintf('Minimum CCW cornering-speed limit: %.3f m/s\n', ...
    minimumCornerSpeedCCW);

fprintf('Minimum CW cornering-speed limit: %.3f m/s\n', ...
    minimumCornerSpeedCW);

fprintf('Margin below minimum cornering-speed limit: %.3f m/s\n', ...
    cornerSpeedMargin);

fprintf('Maximum CCW friction-circle use: %.3f m/s^2\n', ...
    max(combinedAccelerationCCW, [], 'omitnan'));

fprintf('Maximum CW friction-circle use: %.3f m/s^2\n', ...
    max(combinedAccelerationCW, [], 'omitnan'));

fprintf('\nObstacle-selection analysis:\n');

fprintf('Center-path points: %d\n', ...
    numberOfPathPoints);

fprintf('Center-path length: %.3f m\n', ...
    centerPathLength);

fprintf('Selected obstacle index: %d\n', ...
    obstaclePathIndex);

fprintf('Obstacle East coordinate: %.3f m\n', ...
    obstacleCenter(1));

fprintf('Obstacle North coordinate: %.3f m\n', ...
    obstacleCenter(2));

fprintf('Local track width: %.3f m\n', ...
    localTrackWidth);

fprintf('Obstacle length: %.3f m\n', ...
    obstacleLength);

fprintf('Mean CCW approach curvature: %.6f 1/m\n', ...
    meanApproachCurvatureCCW(obstaclePathIndex));

fprintf('Mean CW approach curvature: %.6f 1/m\n', ...
    meanApproachCurvatureCW(obstaclePathIndex));

fprintf('RMS CCW approach curvature: %.6f 1/m\n', ...
    rmsApproachCurvatureCCW(obstaclePathIndex));

fprintf('RMS CW approach curvature: %.6f 1/m\n', ...
    rmsApproachCurvatureCW(obstaclePathIndex));

fprintf('Directional RMS-curvature contrast: %.6f 1/m\n', ...
    maximumDirectionalCurvatureContrast);

% 33. Report the CCW result

fprintf('\nCounter-clockwise result:\n');

fprintf('Collision station: %.3f m\n', ...
    sCollisionCCW);

fprintf('Obstacle-related braking start: %.3f m\n', ...
    sBrakingStartCCW);

fprintf('Braking distance: %.3f m\n', ...
    brakingDistanceCCW);

fprintf('Function-reported braking start: %.3f m\n', ...
    functionSBrakingStartCCW);

fprintf('Function-reported braking distance: %.3f m\n', ...
    functionBrakingDistanceCCW);

fprintf('Maximum braking-region curvature: %.6f 1/m\n', ...
    maximumBrakingCurvatureCCW);

fprintf('Mean braking-region curvature: %.6f 1/m\n', ...
    meanBrakingCurvatureCCW);

fprintf('Maximum lateral acceleration: %.3f m/s^2\n', ...
    maximumLateralAccelerationCCW);

fprintf('Mean lateral acceleration: %.3f m/s^2\n', ...
    meanLateralAccelerationCCW);

fprintf('Maximum longitudinal acceleration: %.3f m/s^2\n', ...
    maximumLongitudinalAccelerationCCW);

fprintf('Maximum lateral friction use: %.2f %%\n', ...
    100 * maximumLateralFrictionUseCCW);

fprintf('Mean lateral friction use: %.2f %%\n', ...
    100 * meanLateralFrictionUseCCW);

fprintf('Maximum combined acceleration: %.3f m/s^2\n', ...
    maximumCombinedAccelerationCCW);

% 34. Report the CW result

fprintf('\nClockwise result:\n');

fprintf('Collision station: %.3f m\n', ...
    sCollisionCW);

fprintf('Obstacle-related braking start: %.3f m\n', ...
    sBrakingStartCW);

fprintf('Braking distance: %.3f m\n', ...
    brakingDistanceCW);

fprintf('Function-reported braking start: %.3f m\n', ...
    functionSBrakingStartCW);

fprintf('Function-reported braking distance: %.3f m\n', ...
    functionBrakingDistanceCW);

fprintf('Maximum braking-region curvature: %.6f 1/m\n', ...
    maximumBrakingCurvatureCW);

fprintf('Mean braking-region curvature: %.6f 1/m\n', ...
    meanBrakingCurvatureCW);

fprintf('Maximum lateral acceleration: %.3f m/s^2\n', ...
    maximumLateralAccelerationCW);

fprintf('Mean lateral acceleration: %.3f m/s^2\n', ...
    meanLateralAccelerationCW);

fprintf('Maximum longitudinal acceleration: %.3f m/s^2\n', ...
    maximumLongitudinalAccelerationCW);

fprintf('Maximum lateral friction use: %.2f %%\n', ...
    100 * maximumLateralFrictionUseCW);

fprintf('Mean lateral friction use: %.2f %%\n', ...
    100 * meanLateralFrictionUseCW);

fprintf('Maximum combined acceleration: %.3f m/s^2\n', ...
    maximumCombinedAccelerationCW);

% 35. Report the directional difference

fprintf('\nCW minus CCW comparison:\n');

fprintf('Braking-distance difference: %.3f m\n', ...
    brakingDistanceDifference);

fprintf('Braking-distance percentage difference: %.2f %%\n', ...
    brakingDistancePercentageDifference);

fprintf('CW-to-CCW braking-distance ratio: %.4f\n', ...
    brakingDistanceCW / brakingDistanceCCW);

fprintf('Intersection-location difference: %.6f m\n', ...
    intersectionLocationDifference);

if brakingDistanceCW <= brakingDistanceCCW

    warning( ...
        ['The CW braking distance is not greater than the ', ...
         'CCW braking distance. Review the selected obstacle ', ...
         'location and curvature profiles.']);

end

